version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: fosl-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fosl_dev
      MYSQL_USER: fosl
      MYSQL_PASSWORD: fosl
    volumes:
      - fosl_mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  fosl_mysql_data:
